"""
FastAPI backend for the mental health chatbot.

Exposes the same chat() pipeline as before (classifier -> safety gate ->
RAG -> LLM), but now as a real HTTP API a frontend can call, with
conversation history persisted in SQLite instead of an in-memory list
that resets on restart.

Run: uvicorn api:app --reload
Then it's available at http://localhost:8000
Interactive API docs (auto-generated by FastAPI) at http://localhost:8000/docs
"""

import os
import json
import uuid
import faiss
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer
from groq import Groq
from dotenv import load_dotenv, find_dotenv

from safety_gate import evaluate_message
import database

load_dotenv(find_dotenv())
database.init_db()

INDEX_DIR = '../knowledge_base_index'

print("Loading embedding model for retrieval...")
embed_model = SentenceTransformer('all-MiniLM-L6-v2')

groq_client = Groq(api_key=os.environ.get('GROQ_API_KEY'))

CRISIS_RESPONSE = (
    "I hear that things feel really heavy right now, and I'm really glad you told me. "
    "Please reach out to Nepal's Mental Health Helpline at 1166 (toll-free, available anytime) - "
    "they're there to listen and help, right now. You don't have to carry this alone."
)

app = FastAPI(title="Mental Health Chatbot API")

# CORS: without this, a browser-based frontend running on a different port
# (e.g. React on localhost:5173) would be BLOCKED by the browser from
# calling this API at all, even though it works fine in tools like curl
# or Postman. This is a browser security feature, not a bug - every
# frontend/backend split needs this.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # for local development only - restrict this before any real deployment
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None  # if not provided, we start a new conversation


class ChatResponse(BaseModel):
    reply: str
    route: str
    label: str
    session_id: str
    retrieved_document: str | None = None


def retrieve_document(category: str, message: str):
    safe_name = category.lower().replace(' ', '_')
    index_path = f'{INDEX_DIR}/{safe_name}.index'
    metadata_path = f'{INDEX_DIR}/{safe_name}_metadata.json'

    if not os.path.exists(index_path):
        return None

    index = faiss.read_index(index_path)
    with open(metadata_path) as f:
        metadata = json.load(f)

    query_vec = embed_model.encode([message], convert_to_numpy=True)
    faiss.normalize_L2(query_vec)
    _, indices = index.search(query_vec, 1)
    return metadata[indices[0][0]]


def generate_response(message: str, retrieved_doc, history: list) -> str:
    if retrieved_doc:
        system_prompt = (
            "You are a warm, supportive mental health chat companion, in an ONGOING conversation - "
            "use the conversation history below to avoid repeating yourself or re-asking things "
            "already covered. "
            "First briefly acknowledge what the person shared, without minimizing it. "
            "If this is early in the conversation and you genuinely need more context, you may ask "
            "ONE gentle follow-up question - but if the person has already shared some detail "
            "(this is turn 2 or later), move toward actually offering support rather than "
            "continuing to ask open-ended questions. People need real suggestions, not endless probing.\n\n"
            "Naturally weave in the following technique, in your own words - don't just paste it verbatim:\n\n"
            f"{retrieved_doc['content']}\n\n"
            "Keep your response brief (3-5 complete sentences - always finish your thought, "
            "never trail off mid-sentence), warm, not clinical, "
            "and never claim to be a therapist."
        )
    else:
        system_prompt = (
            "You are a warm, supportive mental health chat companion, in an ONGOING conversation - "
            "use the conversation history below to avoid repeating yourself or re-asking things "
            "already covered. "
            "Respond briefly and warmly to what the person shared. If this is early in the "
            "conversation, one gentle follow-up question is fine - but don't keep asking for more "
            "detail turn after turn. Never claim to be a therapist."
        )

    messages = [{"role": "system", "content": system_prompt}] + history + [
        {"role": "user", "content": message}
    ]

    response = groq_client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=messages,
        max_tokens=300,
        temperature=0.7,
    )
    return response.choices[0].message.content


@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    session_id = request.session_id or str(uuid.uuid4())
    history = database.get_history(session_id)

    gate_result = evaluate_message(request.message)

    if gate_result['route'] == 'crisis':
        reply = CRISIS_RESPONSE
        retrieved_title = None
    else:
        retrieved_doc = None
        if gate_result['route'] == 'normal' and gate_result['label'] != 'Normal':
            retrieved_doc = retrieve_document(gate_result['label'], request.message)
        reply = generate_response(request.message, retrieved_doc, history)
        retrieved_title = retrieved_doc['title'] if retrieved_doc else None

    # Save both sides of this turn - next request with the same session_id
    # will see this in its history
    database.save_message(session_id, 'user', request.message, gate_result['route'], gate_result['label'])
    database.save_message(session_id, 'assistant', reply, gate_result['route'], gate_result['label'])

    return ChatResponse(
        reply=reply,
        route=gate_result['route'],
        label=gate_result['label'],
        session_id=session_id,
        retrieved_document=retrieved_title,
    )


@app.get("/")
def root():
    return {"status": "Mental health chatbot API is running"}