"""
The complete chatbot pipeline - this is step 5 from our roadmap, tying
together everything we've built:

  message -> safety_gate (classifier + keyword check)
    -> "crisis"        -> fixed pre-written response, no LLM involved
    -> "low_confidence" or label "Normal" -> LLM responds generically, no RAG
    -> otherwise        -> RAG retrieves the right document -> LLM weaves it in

Uses Groq's API for the LLM step (free tier, fast, same pattern as VidMind).

SETUP:
1. Get a free API key at console.groq.com
2. Set it as an environment variable:
   Windows (Git Bash):  export GROQ_API_KEY="your-key-here"
   (Do this every new terminal session, or add it to your shell profile)
3. pip install groq sentence-transformers faiss-cpu

Run from inside src/: python chatbot.py
"""

import os
import json
import faiss
from sentence_transformers import SentenceTransformer
from groq import Groq
from dotenv import load_dotenv, find_dotenv
from safety_gate import evaluate_message

# Automatically finds your .env file wherever it is in the project
# (searches the current folder and parent folders) and loads its
# variables into os.environ - without this, os.environ.get() would
# never see anything from a .env file, only actual terminal exports.
load_dotenv(find_dotenv())

INDEX_DIR = '../knowledge_base_index'

print("Loading embedding model for retrieval...")
embed_model = SentenceTransformer('all-MiniLM-L6-v2')

groq_client = Groq(api_key=os.environ.get('GROQ_API_KEY'))

# Fixed, pre-written - deliberately NOT generated by the LLM.
# See our earlier discussion on why this path never touches the LLM.
CRISIS_RESPONSE = (
    "I hear that things feel really heavy right now, and I'm really glad you told me. "
    "Please reach out to Nepal's Mental Health Helpline at 1166 (toll-free, available anytime) - "
    "they're there to listen and help, right now. You don't have to carry this alone."
)


def retrieve_document(category: str, message: str):
    """Search the category's FAISS index for the most relevant document.
    Returns None if there's no knowledge base file for this category
    (expected for 'Normal' - not an error)."""
    safe_name = category.lower().replace(' ', '_')
    index_path = f'{INDEX_DIR}/{safe_name}.index'
    metadata_path = f'{INDEX_DIR}/{safe_name}_metadata.json'

    if not os.path.exists(index_path):
        return None

    index = faiss.read_index(index_path)
    with open(metadata_path) as f:
        metadata = json.load(f)

    query_vec = embed_model.encode([message], convert_to_numpy=True)
    faiss.normalize_L2(query_vec)
    _, indices = index.search(query_vec, 1)
    return metadata[indices[0][0]]


def generate_response(message: str, retrieved_doc, history: list) -> str:
    if retrieved_doc:
        system_prompt = (
            "You are a warm, supportive mental health chat companion, in an ONGOING conversation - "
            "use the conversation history below to avoid repeating yourself or re-asking things "
            "already covered. "
            "First briefly acknowledge what the person shared, without minimizing it. "
            "If this is early in the conversation and you genuinely need more context, you may ask "
            "ONE gentle follow-up question - but if the person has already shared some detail "
            "(this is turn 2 or later), move toward actually offering support rather than "
            "continuing to ask open-ended questions. People need real suggestions, not endless probing.\n\n"
            "Naturally weave in the following technique, in your own words - don't just paste it verbatim:\n\n"
            f"{retrieved_doc['content']}\n\n"
            "Keep your response brief (3-5 complete sentences - always finish your thought, never trail off mid-sentence), warm, not clinical, "
            "and never claim to be a therapist."
        )
    else:
        system_prompt = (
            "You are a warm, supportive mental health chat companion, in an ONGOING conversation - "
            "use the conversation history below to avoid repeating yourself or re-asking things "
            "already covered. "
            "Respond briefly and warmly to what the person shared. If this is early in the "
            "conversation, one gentle follow-up question is fine - but don't keep asking for more "
            "detail turn after turn. At some point, just be present and supportive with what "
            "you already know. Never claim to be a therapist."
        )

    messages = [{"role": "system", "content": system_prompt}] + history + [
        {"role": "user", "content": message}
    ]

    response = groq_client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=messages,
        max_tokens=300,
        temperature=0.7,
    )
    return response.choices[0].message.content


def chat(message: str, history: list) -> dict:
    gate_result = evaluate_message(message)

    if gate_result['route'] == 'crisis':
        return {'reply': CRISIS_RESPONSE, 'route': 'crisis', 'label': gate_result['label']}

    if gate_result['route'] == 'low_confidence' or gate_result['label'] == 'Normal':
        reply = generate_response(message, retrieved_doc=None, history=history)
        return {'reply': reply, 'route': gate_result['route'], 'label': gate_result['label']}

    retrieved_doc = retrieve_document(gate_result['label'], message)
    reply = generate_response(message, retrieved_doc, history=history)
    return {
        'reply': reply,
        'route': 'normal',
        'label': gate_result['label'],
        'retrieved_document': retrieved_doc['title'] if retrieved_doc else None,
    }


if __name__ == '__main__':
    print("\nMental health chatbot (type 'quit' to exit)\n")
    conversation_history = []
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            break
        result = chat(user_input, conversation_history)
        print(f"\nBot: {result['reply']}")
        print(f"[debug: route={result['route']}, label={result['label']}]\n")

        # Remember this turn for next time - this is what lets the bot
        # actually build on what's already been said instead of treating
        # every message as a fresh, isolated conversation.
        conversation_history.append({"role": "user", "content": user_input})
        conversation_history.append({"role": "assistant", "content": result['reply']})